const userActionTypes  = {
    SET_CURRENT_USER:'SET_CURRENT_USER',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_UP_START:'EMAIL_SIGN_UP_START',
    AUTH_REQUEST_SUCCESS:'AUTH_REQUEST_SUCCESS',
    AUTH_REQUEST_FAILED:'AUTH_REQUEST_FAILED',
    SIGN_OUT:'SIGN_OUT'
}
export default userActionTypes